services:

  tapir:
    image: tapir-local
    build:
      context: .
      dockerfile: tapir.Dockerfile
    environment:
      ALLOWED_HOSTS: ${SERVICE_FQDN_TAPIR},localhost
      SITE_URL: "${SERVICE_URL_TAPIR}"
      DATABASE_URL: "postgresql://tapir:${TAPIR_POSTGRES_PASSWORD:-tapir}@db/tapir"
      STATIC_URL: "${SERVICE_URL_STATIC_HTTP}/"
      ENABLE_RIZOMA_CONTENT: "1"
    command: bash -c "poetry run python ./manage.py collectstatic --clear --noinput && poetry run python ./manage.py migrate && poetry run gunicorn -b 0.0.0.0:80 tapir.wsgi:application"
    logging:
      driver: 'json-file'
      options:
        max-size: '200m'
        max-file: '5'
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      # This volume is also mounted by nginx to serve static files
      - 'tapir-web-static:/app/static'
      - ./rizoma/deploy.env:/app.env:ro

    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  celery:
    image: tapir-local
    build:
      context: .
      dockerfile: tapir.Dockerfile
    restart: unless-stopped
    command: bash -c "poetry install && poetry run celery -A tapir worker -l info"
    volumes:
      - ./rizoma/deploy.env:/app.env:ro
    environment:
      ALLOWED_HOSTS: ${SERVICE_FQDN_TAPIR}
      SITE_URL: "${SERVICE_URL_TAPIR}"
      DATABASE_URL: "postgresql://tapir:${TAPIR_POSTGRES_PASSWORD:-tapir}@db/tapir"
      ENABLE_RIZOMA_CONTENT: "1"
    depends_on:
      - redis
      - tapir

  celery-beat:
    image: tapir-local
    build:
      context: .
      dockerfile: tapir.Dockerfile
    restart: unless-stopped
    command: bash -c "poetry install && poetry run celery -A tapir beat -l info"
    environment:
      ALLOWED_HOSTS: ${SERVICE_FQDN_TAPIR}
      SITE_URL: "${SERVICE_URL_TAPIR}"
      DATABASE_URL: "postgresql://tapir:${TAPIR_POSTGRES_PASSWORD:-tapir}@db/tapir"
      ENABLE_RIZOMA_CONTENT: "1"
      DEBUG: 0
    depends_on:
      - redis
      - tapir

  static-http:
    # serve static files, because django does not
    image: joseluisq/static-web-server:2-alpine
    restart: unless-stopped
    volumes:
      - "tapir-web-static:/static:ro"
    depends_on:
      - tapir
    environment:
      - SERVER_ROOT=/static

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: tapir
      POSTGRES_USER: tapir
      POSTGRES_PASSWORD: ${TAPIR_POSTGRES_PASSWORD:-tapir}
    healthcheck:
      test: pg_isready -d tapir -U tapir
      interval: 30s
      timeout: 15s
      retries: 5
    volumes:
      - 'tapir-db-data:/var/lib/postgresql/data/pgdata'

  # Backend for Celery task queue
  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  tapir-db-data:
  tapir-web-static:
